### ISSUE TITLE
Removing of map function from Html and Sub module

### ISSUE THREAD

**Issue by minedeljkovic** [gcanti/elm-ts#12]
In [this commit](https://github.com/gcanti/elm-ts/commit/e971553d54dfe7e831e430d2892e42c72ab65142#diff-3d86db7c4d764c13d9926ad29b24f1b9) `map` function was removed from `Html` and `Sub` modules.

In original Elm architecture `Sub`, `Cmd` and `Html` are effects that result in a parametric type `Msg`. Idiomatic way of composing `Sub` and `Cmd` effects in Elm architecture are `batch` and `map` and way of composing Html effect is `map`.

This issue is really a question. Why `map` function was removed from Sub and Html?

Of course, `map` over `Sub` is easy to achieve, because `Sub` is really `Observable` which has its own `map` method, but maybe `Observable` should be treated as an implementation detail here (the same way it's treated in `batch` function).

Elm's way of `map` over `Html` is also achievable:
```js
view(model).run(a => dispatch(f(a))
```
Introduction of a `Reader` as a structure for `Html` is, I believe, in collision with original Elm's `Html` effect. `map` of a elm-ts's `Html` (in fact a `Reader`) effect maps function `dom => dom` (I cannot see straight away where would that be usable, since using different renderers is probably not a good idea) while `map` of a Elm's `Html` function maps function `msg => msg`.

**Comment by gcanti** [comment]
> Why map function was removed from Sub?

because it owns a `map` method which is more handy (however I'm fine with re-adding the static function)

> map of a elm-ts's Html (in fact a Reader) effect maps function dom => dom [...] Elm's Html function maps function msg => msg

Oh you are right, my bad

**Comment by minedeljkovic** [comment]
> however I'm fine with re-adding the static function

I would re-add it because of familiarity with Elm itself and to bi consistent with `batch` function.

I am on this if you don't mind.
