### ISSUE TITLE
introduce of e iof to (m: Msg) => Cmd<Msg>

### ISSUE THREAD

**Issue by mattiamanzati** [gcanti/elm-ts#21]
I usually find a lot useful to transform a Msg to a Cmd<Msg>, and I think that's a common scenario; so why don't include this as part of the Cmd module?
Not sure about the names, atm I named them like so, but someone more experienced in fp may know the exact name of "iof"! (or maybe more explicitely fromMsg?)
```typescript
declare const iof: <msg>(msg: msg) => Observable<Task<Option<msg>>>
declare const of: <msg>(task: Task<Option<msg>>) => Observable<Task<Option<msg>>>
```

**Comment by minedeljkovic** [comment]
The fact that a `Cmd` is an `Observable` is an implementation detail and I would advise against relying on that.
`Cmd`, in elm architecture, is a description of effect resulting in a `Msg`, so in case you know in advance what msg value is the result of a `Cmd`, then it is a case of constant effect. Example:
```js
import { perform } from 'elm-ts/lib/Task'
import { task } from 'fp-ts/lib/Task'

const cmd = perform(task.of(undefined), () => 'SomeMessage');
```
There is extremely rare need for a constant effect in typical elm application, so I would rather be explicit about it as in example, then introduce standard helper function.
@mattiamanzati  If your need for constant effects is frequent, may I ask for some concrete use case(s)?

**Comment by mattiamanzati** [comment]
> There is extremely rare need for a constant effect in typical elm application, so I would rather be explicit about it as in example, then introduce standard helper function.

And that's exactly where I am using the constant effects, I have functions like:
`(field: string) => cmd.iof({ type: MSG_END_EDIT, payload: field })`

But now that I see how to use perform, I see that the amount of code is almost the same!
Thanks for the explanation @minedeljkovic !
