### ISSUE TITLE
Invalid http status code results in NetworkError

### ISSUE THREAD

**Issue by minedeljkovic** [gcanti/elm-ts#23]
Every http status code < 200 or >= 300 results in NetworkError, instead of BadStatus or BadUrl error.

**Comment by gcanti** [comment]
Patch released https://github.com/gcanti/elm-ts/releases/tag/0.4.2

**Comment by minedeljkovic** [comment]
After further testing it turned out that axios, in some cases, returns `response` property but with undefined value :(
So #24 introduced a regression, #25 fixes that.
Sorry for the hickup!

**Comment by gcanti** [comment]
@minedeljkovic no problem!
