### ISSUE TITLE
Upgrade to latest libs versions

### ISSUE THREAD

**Issue by sledorze** [gcanti/elm-ts#29]

**Comment by gcanti** [comment]
@StefanoMagrassi is working on this in the `0.5.0` branch

**Comment by sledorze** [comment]
@gcanti @StefanoMagrassi ok great :)

**Comment by StefanoMagrassi** [comment]
@sledorze we didn't talked about a release date yet. maybe @gcanti can publish the 0.5.0 version as `next` dist-tag on npm so we can try it

**Comment by StefanoMagrassi** [comment]
@sledorze the v0.5.1 was released in the `next` dist-tag on npm, if you want to check it out :wink:
