### ISSUE TITLE
Stop/unsubscribe application

### ISSUE THREAD

**Issue by StefanoMagrassi** [gcanti/elm-ts#37]
`elm-ts` should make available a way to stop/cancel a running application, namely unsubscribing from streams generated by `program`.

This is needed in order to cleanup resources when the application is somehow "unmounted" and to avoid duplicated events when it is "remounted".

I thought about 2 possible solutions.

**1) non breaking:**
passing an optional parameter to the `run` function and using [`takeUntil`](https://rxjs.dev/api/operators/takeUntil) operator as suggested [here](https://medium.com/@benlesh/rxjs-dont-unsubscribe-6753ed4fda87)

```ts
declare function run<Model, Msg>(program: Program<Model, Msg>, stop$?: Observable<any>): Observable<Model>
```

**2) breaking:**
changing the return type of the `run` function in order to provide to the consumer the related `unsubscribe` function for each subscribed stream

```ts
interface Return<Model> {
  model$: Observable<Model>;
  unsubscribeCmd: () => void;
  unsubscribeSub: () => void;
}

declare function run<Model, Msg>(program: Program<Model, Msg>): Return<Model>
```

I think that the solution n° 1 could be the best. What is your opinion @gcanti?

**Comment by StefanoMagrassi** [comment]
To be more accurate, solution number 1 could be:

```ts
import {Observable, EMPTY} from 'rxjs';
import {takeUntil} from 'rxjs/operators'

function run<Model, Msg>(
  program: Program<Model, Msg>,
  stop$: Observable<any> = EMPTY
): Observable<Model> {
  const { dispatch, cmd$, sub$, model$ } = program

  cmd$.pipe(takeUntil(stop$)).subscribe(task => task().then(O.map(dispatch)))
  sub$.pipe(takeUntil(stop$)).subscribe(dispatch)

  return model$
}
```
And solutione number 2 could be simplified to:

```ts
interface Return<Model> {
  model$: Observable<Model>;
  cleanup: () => void;
}

function run<Model, Msg>(program: Program<Model, Msg>): Return<Model> {
 const { dispatch, cmd$, sub$, model$ } = program

  const cmdUnsubscribe = cmd$.subscribe(task => task().then(O.map(dispatch)))
  const subUnsubscribe = sub$.subscribe(dispatch)

  return {
    model$,
    cleanup: () => {
      cmdUnsubscribe();
      subUnsubscribe();
    }
  }
}
```

**Comment by gcanti** [comment]
**3) non breaking:**

```ts
import { Observable } from 'rxjs'
import { takeUntil } from 'rxjs/operators'

export function withStop<Model, Msg>(program: Program<Model, Msg>, stop$: Observable<unknown>): Program<Model, Msg> {
  const { dispatch, cmd$, sub$, model$ } = program
  return { dispatch, cmd$: cmd$.pipe(takeUntil(stop$)), sub$: sub$.pipe(takeUntil(stop$)), model$ }
}
```

**Comment by StefanoMagrassi** [comment]
uhmmmm, but the logic of "stopping/cleaning up" is something more related to `run` than to `program`.

Maybe a we can use the same strategy with `run`:

```ts
import {Observable} from 'rxjs';
import {takeUntil} from 'rxjs/operators'

function runWithStop<Model, Msg>(
  program: Program<Model, Msg>,
  stop$: Observable<unknown>
): Observable<Model> {
  const { dispatch, cmd$, sub$, model$ } = program

  cmd$.pipe(takeUntil(stop$)).subscribe(task => task().then(O.map(dispatch)))
  sub$.pipe(takeUntil(stop$)).subscribe(dispatch)

  return model$
}
```

**Comment by mattiamanzati** [comment]
Uhm, not sure but maybe introduce something like a "runv2" like fp-ts v1 did and return alongside the dispatch, cmd, model, etc... also a unsubscribe method to stop the application? previous run implementation body can be replaced by calling v2 run and removing unsubscribe return method

**Comment by StefanoMagrassi** [comment]
@mattiamanzati because the package is in a "pre-1" version we can make breaking changes without _breaking_ the semver contract, so adding a "v2" API should not be needed.

 And I think that the strategy with `takeUntil` could be more flexible than exposing an unsubscribe/cleanup function (please check [this post](https://medium.com/@benlesh/rxjs-dont-unsubscribe-6753ed4fda87))

**Comment by mattiamanzati** [comment]
Waaaaait, but could'nt we just modify the program() result before passing it to run?

**Comment by StefanoMagrassi** [comment]
> Waaaaait, but could'nt we just modify the program() result before passing it to run?

yep, but as I wrote before I think that the stopping logic should be related to the `run` function.

BTW modifying the `program`'s output could be a quick solution that can be implemented at the specific application level without changing the package APIs

**Comment by gcanti** [comment]
> but the logic of "stopping/cleaning up" is something more related to run than to program

@StefanoMagrassi not sure what you mean

- a `Program` is a value that describes how a program behaves (whether it "stops" or not _is_ behavior), `run` should just run a program
- a combinator `Program -> Program` is a pretty elegant and idiomatic solution in functional programming
- moreover, it doesn't require any breaking change

**Comment by StefanoMagrassi** [comment]
> a Program is a value that describes how a program behaves (whether it "stops" or not is behavior), run should just run a program

In this light also "running" would be a `program`'s behaviour ;)

> a combinator Program -> Program is a pretty elegant and idiomatic solution in functional programming
> moreover, it doesn't require any breaking change

just like a `runWithStop` function ;)

I'm firmly convinced that starting/running and stopping a program, which is a inert entity, is a responsibility of an another component, like `run` in our case (otherwise `.subscribe` would not be called there)

**Comment by gcanti** [comment]
> In this light also "running" would be a program's behaviour ;)

Well, running is... running, like running a `Task<A>`: say you want to `console.log` the value returned by a task, you can write a combinator `Task<A> => Task<A>`. Sure you could run the task and _then_ call `console.log`, but that's not elegant at all.

Note that I used "stops" because of the sematic of this issue, but you are really combining streams, and nothing stops you to define more general combinators

```ts
import { pipe } from 'fp-ts/lib/pipeable'
import { Observable } from 'rxjs'
import { takeUntil } from 'rxjs/operators'
import { Cmd } from '../src/Cmd'
import { Program } from '../src/Platform'
import { Sub } from '../src/Sub'

export function withCmd<Msg>(
  f: (cmd: Cmd<Msg>) => Cmd<Msg>
): <Model>(program: Program<Model, Msg>) => Program<Model, Msg> {
  return program => {
    const { cmd$, ...rest } = program
    return { cmd$: f(cmd$), ...rest }
  }
}

export function withSub<Msg>(
  f: (sub: Sub<Msg>) => Sub<Msg>
): <Model>(program: Program<Model, Msg>) => Program<Model, Msg> {
  return program => {
    const { sub$, ...rest } = program
    return { sub$: f(sub$), ...rest }
  }
}

export function withStop<Model, Msg>(program: Program<Model, Msg>, stop$: Observable<unknown>): Program<Model, Msg> {
  return pipe(
    program,
    withCmd(cmd$ => cmd$.pipe(takeUntil(stop$))),
    withSub(sub$ => sub$.pipe(takeUntil(stop$)))
  )
}
```

**Comment by StefanoMagrassi** [comment]
> Well, running is... running, like running a Task<A>: say you want to console.log the value returned by a task, you can write a combinator Task<A> => Task<A>. Sure you could run the task and then call console.log, but that's not elegant at all.

I don't think that is the same situation... `console.log` isn't related to the `Task` execution

> Note that I used "stops" because of the sematic of this issue, but you are really combining streams, and nothing stops you to define more general combinators

Using a stream with the `takeUntil` operator is an implementation detail: the main issue is the capability of stopping the application.

**Comment by StefanoMagrassi** [comment]
Ok, you convinced me. I'll prepare a PR today or in the next few days
