### ISSUE TITLE
Is React's `useEffect` supposed to work within elm-ts' view functions? If not, how can I perform side effect which is dependent on first rendering the component?

### ISSUE THREAD

**Issue by yyccnn** [gcanti/elm-ts#51]
First, thank you for this great library.
I am trying to use a graphing library within elm-ts.
To do so, I need to be able to call some impure, plot-generating function after a `div` described by the view function has been rendered.
I was able to do that with React using `useEffect` within a component.

However, trying to do the same thing within the view function in elm-ts fails. I am getting the following error:
```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
...
```
So I examined these hypotheses one by one:
1. I definitely ruled out the mismatching-versions hypothesis. 
2. Even though that might not be enough to discard the second hypothesis completely, the `eslint-plugin-react-hooks` could not detect any breach in my code with regard to the Rules of Hooks. 
3. As for the multiple-react-versions hypothesis, I tried the fixes suggested [here](https://robkendal.co.uk/blog/2019-12-22-solving-react-hooks-invalid-hook-call-warning) and [there](https://www.ibenic.com/gutenberg-components-and-invalid-hook-call-error-in-react-what-do-do/). Neither worked for me.

What should I do? Is there a way to make `useEffect` work within elm-ts view functions?
If not, is using a Command with Subscriptions (two topics I have yet to read in depth in Elm's documentation, admittedly) a viable alternative? If so, how would I know that the expected `div` has already been generated and how would I use the graphing library's specific event handlers to fire messages that will be fed to the update function?

**Comment by minedeljkovic** [comment]
[This rule](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-from-react-functions) forbids using hooks in plain JS functions, and view in elm-ts is just a plain function.
But you can always extract the part of vdom that needs hooks into it's own component, like this:
```js
const Foo = (props: Props) => {
  useEffect(/*...*/)
  return <div />
}

const viewFoo = (props: Props): Html<Msg> =>
  _ => <Foo {...props} />
```

**Comment by yyccnn** [comment]
@minedeljkovic Thank you for your helpful reply. It has solved my issue.
